### PR TITLE
feat: expose 443:443/udp in nginx service

### LINKED ISSUE #1354: Port map 443/udp in nginx service to allow HTTP3
**Is your feature request related to a problem? Please describe.**

I'm using the `macbre/nginx-http3` image for the nginx service so my apps can use HTTP3:

```json5
// config-override.json
{
  "nginxImageName": "macbre/nginx-http3:1.21.6"
}
```

Unlike HTTP1 and 2 which are based on TCP, HTTP3 uses the UDP protocol. Unfortunately, HTTP3 connections can't be established because no UDP port is mapped to the nginx container: https://github.com/caprover/caprover/blob/master/src/user/system/LoadBalancerManager.ts#L564-L577.

**Describe the solution you'd like**

Either add `443/udp` to the array of mapped ports, or make the ports array configurable via `config-override.json`.

**Describe alternatives you've considered**

Remember to manually update the port config every time the nginx service is created using
`docker service update --publish-add published=443,target=443,mode=host,protocol=udp captain-nginx`. Error-prone and tedious 😅

### PR DESCRIPTION
**Pull request by jonaskuske**
fix #1354

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks for the PR. But this is not a commonly used port. As mentioned in our design goals, we keep the default use cases to those are the commonly used. I was gonna mention this, but it looks like you already know this that you can simply use `docker update` to add this UDP port for your use case. 

Since using a 3rd party nginx image itself requires customization, you can add this to the same customization script. So there won't be any customization overhead. Something like this `setup-caprover.sh`:
```bash
#!/bin/bash
docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
sleep 60
echo  "{\"nginxImageName\": \"macbre/nginx-http3:1.21.6\"}" >  /captain/data/config-override.json
docker service update --publish-add published=443,target=443,mode=host,protocol=udp captain-nginx
```

image

**Comment by jonaskuske** [comment]
Fair enough, and thanks for the detailed response! :)

**Comment by osxisl** [comment]
@githubsaturn do you have any plans for http/3 support in caprover by default or as an option?
Cloudflare reports usage ~31% https://radar.cloudflare.com/explorer?dataSet=http&groupBy=http_version&filters=botClass%253DLikely_Human&dt=52w
and ~95% of all users tracked by https://caniuse.com/http3 support it.

**Comment by ariaieboy** [comment]
@githubsaturn 
the docker nginx supports http3 by default now. 
by updating the nginx version and opening 443/udp we can have http3 support by default on caprover.

**Comment by githubsaturn** [comment]
What version of nginx should we upgrade to?

**Comment by ariaieboy** [comment]
> What version of nginx should we upgrade to?

I tested with 1.27.2 today and it works perfectly fine with caprover but I need to open up on 443 manualy

But I think since 1.25.0 it contains the http3 code

**Comment by ariaieboy** [comment]
image

Yes nginx docker image >=1.25.0 supports http3 module by default.

**Comment by githubsaturn** [comment]
Sounds good! Let's reopen and merge!

**Comment by githubsaturn** [comment]
Feel free to send another PR to update the nginx version
https://github.com/caprover/caprover/blob/master/src/utils/CaptainConstants.ts#L44

**Comment by jonaskuske** [comment]
Woohoo, back from the dead, just in time for Halloween – thanks for merging! 🎃

**Pull request merged**
