### PR TITLE
Adding support for overwriting app defaults NGINX config

### PR DESCRIPTION
**Pull request by janericwinkelmann**
This pull request adds the ability to customise the default NGINX config that every app created will use. It closes the discussion on #977

### CODE REVIEW

**Comment by kaaax0815** [comment]
Does this work? Why is it ignored?

**Comment by githubsaturn** [comment]
It just fails the formatter check, needs a simple refortmatting to be be merged.

**Comment by janericwinkelmann** [comment]
@githubsaturn Sorry for this late response, I fixed the formatting issues so this should be good to go. :)

**Comment by githubsaturn** [comment]
Thanks!

**Comment by wizztjh** [comment]
any plans to update the documents on how to ip whitelist and etc with this new feature?

**Comment by githubsaturn** [comment]
This PR is not published yet, it's only available on edge. But feel free to add a section at the bottom of [this page](https://caprover.com/docs/best-practices.html) and add the content there.

**Pull request merged**
