### PR TITLE
Fix app config update for global mode services

### PR DESCRIPTION
**Pull request by VoidMonk**
Currently, CapRover v1.10.1 is not able to create services in global mode. A workaround https://github.com/caprover/caprover/issues/1699#issuecomment-1469012497 was suggested to create a global service using Docker CLI, then adding the app in CapRover, but it still doesn't allow for app config updates from the UI due to an 'instance count' validation for non-replicated services.

This PR simplifies the validation limiting it to replicated mode services only, and allowing updates of global mode services to go through.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks!

**Comment by githubsaturn** [comment]
Looks like the edge version build fail due to an unrelated reason. Will fix it soon.

**Comment by VoidMonk** [comment]
Thanks for merging!

Looks like the action to build & push the edge image failed.

**Comment by VoidMonk** [comment]
Thanks for merging!

Yes, please fix the action for edge image update.

**Pull request merged**
